export * from "./Home"
export * from "./Registro"
export * from "./Busqueda"
export * from "./RegistrarWally"
export * from "./RegistrarTorneo"
export * from "./ListaTorneo"
export * from "./CanchasWally"
export * from "./BusquedaTorneo"